### ISSUE TITLE
Long text in sidebar overflows container (Chrome, Safari)

### ISSUE THREAD

**Issue by vicmeow** [vicmeow/testframework#6]
### **Type of Issue**

- [X] Bug
- [ ] Enhancement (change/improvement)

## **Description**

When a project/run/test case/step has a name that is too long, the text overflows its container in the sidebar.

## **Steps to reproduce**

1. Navigate to a project/run/test case/step with a long name

![localhost_8080_projects_project 201_61c9dca5-4fd2-4cfa-b0de-f9f5957bff0d_tf-0001-planfahrt-13_verspaetung_vereinigte_fahrt-showcase_verspaetung-showcase 1](https://user-images.githubusercontent.com/25737281/41645814-6196d778-7472-11e8-9b1f-629a694fc88b.png)

## **Possible Solution**

- Try word-break: break-all;

## **Your Environment (if relevant)**

- Browser Name and version: Safari (11.1.1), Chrome (v. 67.0.3396.87)

**Comment by ninnivictoria** [comment]
Had to use word-break: break-all because break-word is not widely supported.
